name: Update Server Tips
on:
  workflow_dispatch:
  schedule:
  - cron: '0 1 * * *'

jobs:
  update-server-tips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@latest

      - name: Set up Python
        uses: actions/setup-python@latest
        with:
          python-version: '3.x'

      - name: Run update script to select next random tips available
        run: python server_tips.py

      - name: Commit and Push changes
        uses: EndBug/add-and-commit@latest
        with:
          author_name: TheKingTermux
          author_email: 50316075+TheKingTermux@users.noreply.github.com
          message: "Otomatis: Update server tips acak"
          add: 'README.md status.json' 
