name: Update Meme Image
on:
  workflow_dispatch:
  schedule:
  - cron: '0 1 * * *'

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6.3.0
        with:
          python-version: '3.x'

      - name: Run update script to select next random meme available
        run: python meme.py

      - name: Commit and Push changes
        uses: EndBug/add-and-commit@latest
        with:
          author_name: TheKingTermux
          author_email: 50316075+TheKingTermux@users.noreply.github.com
          message: "Otomatis: Update gambar meme acak"
          add: 'README.md status.json' 
